effort_jointed_robot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort Controllers
  base_to_arm_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_to_arm
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  # PID gains
  gazebo_ros_control:
    pid_gains:
      base_to_arm:
        p: 100.0
        i: 0.01
        d: 10.0
