positional_jointed_robot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  base_to_arm_positional_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_arm
    pid: { p: 1.0, i: 0.0, d: 0.0 }

  # PID gains
  gazebo_ros_control:
    pid_gains:
      base_to_arm:
        p: 1.0
        i: 0.0
        d: 0.0
