car:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # right_front_wheel_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: right_front_to_right_front_axle_joint

  # left_front_wheel_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: left_front_to_left_front_axle_joint

  right_rear_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_rear_to_right_rear_axle_joint

  left_rear_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_rear_to_left_rear_axle_joint

  # right_front_shock_controller:
  #   type: position_controllers/JointPositionController
  #   joint: chassis_to_right_front_shock_mount__column_joint

  # left_front_shock_controller:
  #   type: position_controllers/JointPositionController
  #   joint: chassis_to_left_front_shock_mount__column_joint

  # PID gains (if needed)
  gazebo_ros_control:
    pid_gains:
      right_front_to_right_front_axle_joint: { p: 1.0, i: 0.00, d: 0.0 }
      left_front_to_left_front_axle_joint: { p: 1.0, i: 0.00, d: 0.0 }
      right_rear_to_right_rear_axle_joint: { p: 1.0, i: 0.00, d: 0.0 }
      left_rear_to_left_rear_axle_joint: { p: 1.0, i: 0.00, d: 0.0 }
      chassis_to_right_front_shock_mount_column_joint:
        { p: 1.0, i: 0.00, d: 0.0 }
      chassis_to_left_front_shock_mount_column_joint:
        { p: 1.0, i: 0.00, d: 0.0 }
