<?xml version="1.0"?>
<robot name="car"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Import the wheel macro -->
    <xacro:include filename="wheel.xacro" />

    <!-- Define robot parameters -->
    <xacro:property name="body_length" value="0.5" />
    <xacro:property name="body_width" value="0.3" />
    <xacro:property name="body_height" value="0.1" />
    <xacro:property name="body_mass" value="5.0" />

    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="wheel_mass" value="1.0" />

    <!-- Robot body -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 0.8 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${body_mass}"/>
            <inertia ixx="${(1/12) * body_mass * (body_width*body_width + body_height*body_height)}" ixy="0" ixz="0" iyy="${(1/12) * body_mass * (body_length*body_length + body_height*body_height)}" iyz="0" izz="${(1/12) * body_mass * (body_length*body_length + body_width*body_width)}" />
        </inertial>
    </link>

    <!-- Use the wheel macro to create a wheel -->
    <xacro:wheel id="wheel" radius="${wheel_radius}" width="${wheel_width}" mass_kg="${wheel_mass}" />

    <!-- Joint connecting the body to the wheel -->
    <joint name="right_rear_to_right_rear_axle_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel"/>
        <origin xyz="${body_length/2} 0 ${-body_height/2}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Transmission for the wheel joint -->
    <transmission name="wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_rear_to_right_rear_axle_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/car</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo>

</robot>